import { logRedactedError } from '@hyperquote/ui/logging/redacted-error'

type ServerLogEvent =
	| 'website.auth.send_otp.supabase_error'
	| 'website.auth.send_otp.unexpected_error'
	| 'website.auth.verify_otp.supabase_error'
	| 'website.auth.verify_otp.unexpected_error'
	| 'website.auth.email_signup.supabase_error'
	| 'website.auth.email_signup.unexpected_error'
	| 'website.auth.email_signin.unexpected_error'
	| 'website.auth.password_reset_request.supabase_error'
	| 'website.auth.password_reset_request.unexpected_error'
	| 'website.auth.password_reset_verify.supabase_error'
	| 'website.auth.password_reset_update.supabase_error'
	| 'website.auth.password_reset_complete.unexpected_error'
	| 'website.auth.check_account.unexpected_error'
	| 'website.auth.create_account.supabase_error'
	| 'website.auth.create_account.unexpected_error'
	| 'website.auth.claim_account.supabase_error'
	| 'website.auth.claim_account.unexpected_error'
	| 'website.auth.activity.supabase_error'
	| 'website.auth.sign_out.supabase_error'
	| 'website.ai.audit_rpc_failed'
	| 'website.ai.audit_unexpected_error'
	| 'website.catalog.categories.supabase_error'
	| 'website.catalog.category_image.supabase_error'
	| 'website.catalog.public_catalog.supabase_error'
	| 'website.catalog.product_by_slug.supabase_error'
	| 'website.quote_request.saved_drafts.unexpected_error'
	| 'website.quote_request.save.unexpected_error'
	| 'website.quote_request.submit.unexpected_error'
	| 'website.support.ticket_create_failed'
	| 'website.support.unexpected_error'

export function logWebsiteServerError(event: ServerLogEvent, error: unknown) {
	logRedactedError({ source: 'website', event, error })
}
