export interface CountryCodeOption {
	code: string
	label: string
}

export const ORDER_ASSOCIATE_COUNTRY_CODES: CountryCodeOption[] = [
	{ code: '+20', label: 'Egypt' },
	{ code: '+966', label: 'Saudi Arabia' },
	{ code: '+971', label: 'United Arab Emirates' },
	{ code: '+965', label: 'Kuwait' },
	{ code: '+974', label: 'Qatar' },
	{ code: '+973', label: 'Bahrain' },
	{ code: '+968', label: 'Oman' },
	{ code: '+962', label: 'Jordan' },
	{ code: '+961', label: 'Lebanon' },
	{ code: '+964', label: 'Iraq' },
	{ code: '+963', label: 'Syria' },
	{ code: '+970', label: 'Palestine' },
	{ code: '+212', label: 'Morocco' },
	{ code: '+213', label: 'Algeria' },
	{ code: '+216', label: 'Tunisia' },
	{ code: '+218', label: 'Libya' },
	{ code: '+249', label: 'Sudan' },
	{ code: '+967', label: 'Yemen' },
	{ code: '+1', label: 'United States / Canada' },
	{ code: '+44', label: 'United Kingdom' },
	{ code: '+33', label: 'France' },
	{ code: '+49', label: 'Germany' },
	{ code: '+39', label: 'Italy' },
	{ code: '+34', label: 'Spain' },
	{ code: '+90', label: 'Turkey' },
	{ code: '+91', label: 'India' },
	{ code: '+92', label: 'Pakistan' },
	{ code: '+880', label: 'Bangladesh' },
	{ code: '+86', label: 'China' },
	{ code: '+81', label: 'Japan' },
	{ code: '+82', label: 'South Korea' },
	{ code: '+234', label: 'Nigeria' },
	{ code: '+27', label: 'South Africa' },
	{ code: '+61', label: 'Australia' },
]
