import type { WizardStep } from '../registry'

export const steps: WizardStep[] = [
  {
    id: 'install-app',
    titleKey: 'docs.wizard.for-drivers.steps.installApp.title',
    bodyKey: 'docs.wizard.for-drivers.steps.installApp.body',
    title: 'Install the App',
    body: 'Download the HyperQuote Driver app from the App Store or Google Play. It works on any modern smartphone and requires location permissions for GPS tracking during deliveries.',
    illustration: 'signup',
    tip: 'docs.wizard.for-drivers.steps.installApp.tip',
    tipText: 'Allow background location access when prompted — this lets dispatch track your position even when the screen is off.',
  },
  {
    id: 'login-setup',
    titleKey: 'docs.wizard.for-drivers.steps.loginSetup.title',
    bodyKey: 'docs.wizard.for-drivers.steps.loginSetup.body',
    title: 'Log In and Set Up',
    body: 'Sign in with your mobile number and the verification code sent to your WhatsApp. Your vehicle details and delivery zone are pre-configured by dispatch — just confirm and you are ready to go.',
    illustration: 'verify',
    tipText: 'Your login works offline too. Once signed in, the app syncs assignments even without a stable connection.',
  },
  {
    id: 'view-assignments',
    titleKey: 'docs.wizard.for-drivers.steps.viewAssignments.title',
    bodyKey: 'docs.wizard.for-drivers.steps.viewAssignments.body',
    title: 'View Your Assignments',
    body: 'Your daily delivery assignments appear on the home screen, sorted by route. Each one shows the pickup location, delivery address, items, quantities, and any special instructions from the customer.',
    illustration: 'browse',
    tipText: 'Assignments are optimized by route — follow the suggested order to save time and fuel.',
  },
  {
    id: 'start-delivery',
    titleKey: 'docs.wizard.for-drivers.steps.startDelivery.title',
    bodyKey: 'docs.wizard.for-drivers.steps.startDelivery.body',
    title: 'Start a Delivery',
    body: 'Tap "Start" on an assignment to begin. The app activates GPS tracking and notifies the customer that their delivery is on the way. Verify the loaded materials match the delivery note before departing.',
    illustration: 'submit',
    tip: 'docs.wizard.for-drivers.steps.startDelivery.tip',
    tipText: 'Central Cairo has a truck ban from 6AM to midnight. The app will warn you if your route passes through restricted zones.',
  },
  {
    id: 'navigate-route',
    titleKey: 'docs.wizard.for-drivers.steps.navigateRoute.title',
    bodyKey: 'docs.wizard.for-drivers.steps.navigateRoute.body',
    title: 'Navigate Your Route',
    body: 'Follow the built-in map with turn-by-turn directions to the delivery site. The map works offline using downloaded tiles, so you stay on track even in areas with poor signal.',
    illustration: 'track',
    tipText: 'Prayer time buffers are built into your ETAs automatically. No need to adjust manually.',
  },
  {
    id: 'collect-proof',
    titleKey: 'docs.wizard.for-drivers.steps.collectProof.title',
    bodyKey: 'docs.wizard.for-drivers.steps.collectProof.body',
    title: 'Collect Proof of Delivery',
    body: 'At the site, take photos of the delivered materials and capture the customer signature on screen. If anything is damaged, use the damage report form — photos and notes are required before marking complete.',
    illustration: 'search',
    tip: 'docs.wizard.for-drivers.steps.collectProof.tip',
    tipText: 'Photos are timestamped and geotagged automatically. Take clear shots of every pallet or bundle.',
  },
  {
    id: 'complete-delivery',
    titleKey: 'docs.wizard.for-drivers.steps.completeDelivery.title',
    bodyKey: 'docs.wizard.for-drivers.steps.completeDelivery.body',
    title: 'Complete the Delivery',
    body: 'Mark the delivery as complete and all proof is uploaded automatically. If you are offline, everything queues locally and syncs the moment you reconnect. Move on to your next assignment.',
    illustration: 'support',
    tipText: 'Offline mode keeps everything safe. Your photos, signatures, and status updates sync as soon as you have signal.',
  },
]
