import type { WizardStep } from '../registry'

export const steps: WizardStep[] = [
  {
    id: 'portal-overview',
    titleKey: 'docs.wizard.for-customers.steps.portalOverview.title',
    bodyKey: 'docs.wizard.for-customers.steps.portalOverview.body',
    title: 'Your Portal Home',
    body: 'The customer portal opens to a clean workspace with AI chat at the center and two main entry points: Orders and Market. Everything you need is inside these glass windows — no cluttered dashboards.',
    illustration: 'browse',
    tip: 'docs.wizard.for-customers.steps.portalOverview.tip',
    tipText: 'Try the AI chat — ask "What did I order last month?" or "I need cement for a 200sqm slab" and it will draft a material list for you.',
  },
  {
    id: 'create-project',
    titleKey: 'docs.wizard.for-customers.steps.createProject.title',
    bodyKey: 'docs.wizard.for-customers.steps.createProject.body',
    title: 'Create a Project',
    body: 'Organize your work by project — give it a name, site address, and delivery location. All quotes, orders, and deliveries for that site are grouped together so nothing gets lost across multiple jobs.',
    illustration: 'signup',
    tipText: 'Managing 5+ sites? Projects keep each one separate with its own material lists and delivery history.',
  },
  {
    id: 'build-material-list',
    titleKey: 'docs.wizard.for-customers.steps.buildMaterialList.title',
    bodyKey: 'docs.wizard.for-customers.steps.buildMaterialList.body',
    title: 'Build Your Material List',
    body: 'Add materials by searching the catalog, uploading a CSV or bill of materials, using the quick order pad, or simply telling the AI what you are building. Save drafts and come back anytime.',
    illustration: 'search',
    link: { to: '/market', labelKey: 'docs.wizard.for-customers.steps.buildMaterialList.link', label: 'Browse Materials' },
    tipText: 'The AI estimator can generate a full material list from a project description — just add quantities and submit.',
  },
  {
    id: 'request-quote',
    titleKey: 'docs.wizard.for-customers.steps.requestQuote.title',
    bodyKey: 'docs.wizard.for-customers.steps.requestQuote.body',
    title: 'Request a Quote',
    body: 'Submit your material list as a quote request. We source prices from multiple suppliers in parallel and build you a single consolidated quote — usually within 4 hours for common materials.',
    illustration: 'submit',
    tip: 'docs.wizard.for-customers.steps.requestQuote.tip',
    tipText: 'Quotes include 14% VAT as a separate line. B2B buyers can reclaim input VAT, so your net cost is the pre-VAT price.',
  },
  {
    id: 'review-quote',
    titleKey: 'docs.wizard.for-customers.steps.reviewQuote.title',
    bodyKey: 'docs.wizard.for-customers.steps.reviewQuote.body',
    title: 'Review Your Quote',
    body: 'Your quote arrives with a full line-item breakdown, delivery timeline, and validity period. Accept it as-is, or negotiate — every counter-offer is version-tracked so you never lose context.',
    illustration: 'quote',
    tipText: 'Steel and cement quotes are valid for 5-7 days due to price volatility. Stable materials get up to 14 days.',
  },
  {
    id: 'accept-order',
    titleKey: 'docs.wizard.for-customers.steps.acceptOrder.title',
    bodyKey: 'docs.wizard.for-customers.steps.acceptOrder.body',
    title: 'Accept and Confirm',
    body: 'Accept the quote and it converts to a confirmed order instantly. Purchase orders go out to suppliers automatically. You will receive a confirmation with your expected delivery window.',
    illustration: 'verify',
    tipText: 'New customers: 50% advance payment by certified bank cheque, 50% on delivery. Credit terms available after a few successful orders.',
  },
  {
    id: 'track-delivery',
    titleKey: 'docs.wizard.for-customers.steps.trackDelivery.title',
    bodyKey: 'docs.wizard.for-customers.steps.trackDelivery.body',
    title: 'Track Your Delivery',
    body: 'Follow your order through five stages: Confirmed, Being Prepared, Out for Delivery, Delivered, and Invoice Generated. Live GPS tracking shows exactly where your delivery is on a map.',
    illustration: 'track',
    link: { to: '/market', labelKey: 'docs.wizard.for-customers.steps.trackDelivery.link', label: 'View Orders' },
    tipText: 'Deliveries to central Cairo are scheduled outside the 6AM-midnight truck ban window.',
  },
  {
    id: 'manage-payments',
    titleKey: 'docs.wizard.for-customers.steps.managePayments.title',
    bodyKey: 'docs.wizard.for-customers.steps.managePayments.body',
    title: 'Manage Payments',
    body: 'View all invoices, delivery notes, and payment records in one place. Pay by wire transfer, certified cheque, cash on delivery, or letter of credit. Every invoice is ETA-compliant with a digital signature.',
    illustration: 'support',
    tip: 'docs.wizard.for-customers.steps.managePayments.tip',
    tipText: 'All invoices are submitted electronically to the Egyptian Tax Authority in real time — no manual filing needed on your end.',
  },
]
