/**
 * Quote request server functions.
 * Submit, save draft, get drafts, and AI-assisted parsing.
 * Dev mode fallback when Supabase not configured.
 */
import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { getServerSession } from '@hyperquote/auth'

// ============================================================================
// Input Schemas
// ============================================================================

const quoteItemSchema = z.object({
  productId: z.string().uuid().optional(),
  customerDescription: z.string().min(1),
  quantity: z.number().positive(),
  unitOfMeasure: z.string(),
  notes: z.string().optional(),
  sortOrder: z.number(),
  matchConfidence: z.number().optional(),
  isUnmatched: z.boolean().optional(),
})

const submitQuoteRequestInput = z.object({
  items: z.array(quoteItemSchema).min(1),
  deliveryAddressId: z.string().uuid().optional(),
  deliveryDate: z.string().optional(),
  notes: z.string().optional(),
  projectId: z.string().uuid().optional(),
  attachmentUrls: z.array(z.string()).optional(),
  approvalRequired: z.boolean().optional(),
  idempotencyKey: z.string().uuid(),
})

const saveDraftInput = z.object({
  draftId: z.string().uuid().optional(),
  items: z.array(quoteItemSchema),
  deliveryAddressId: z.string().uuid().optional(),
  deliveryDate: z.string().optional(),
  notes: z.string().optional(),
  projectId: z.string().uuid().optional(),
  attachmentUrls: z.array(z.string()).optional(),
})

const parseWithAIInput = z.object({
  text: z.string().min(1),
})

// ============================================================================
// Types
// ============================================================================

export interface ParsedItem {
  productName: string
  quantity: number
  unitOfMeasure: string
  notes?: string
  matchConfidence: number
}

// ============================================================================
// Helper: check if Supabase is configured
// ============================================================================

function isSupabaseConfigured(): boolean {
  return !!(
    process.env.SUPABASE_URL &&
    process.env.SUPABASE_URL !== 'https://placeholder.supabase.co' &&
    process.env.SUPABASE_ANON_KEY &&
    process.env.SUPABASE_ANON_KEY !== 'placeholder'
  )
}

// ============================================================================
// submitQuoteRequest
// ============================================================================

export const submitQuoteRequest = createServerFn()
  .inputValidator(submitQuoteRequestInput)
  .handler(
    async ({
      data: input,
    }): Promise<{ requestId: string; reference: string }> => {
      // Dev mode fallback
      if (!isSupabaseConfigured()) {
        const mockId = crypto.randomUUID()
        const year = new Date().getFullYear()
        const seq = String(Math.floor(Math.random() * 99999)).padStart(5, '0')
        return {
          requestId: mockId,
          reference: `QR-${year}-${seq}`,
        }
      }

      const session = await getServerSession({
        supabaseUrl: process.env.SUPABASE_URL!,
        supabaseAnonKey: process.env.SUPABASE_ANON_KEY!,
      })

      if (!session) {
        throw new Error('Unauthorized')
      }

      // Dynamic import to keep Supabase off the client bundle
      const { createClient } = await import('@supabase/supabase-js')
      const supabase = createClient(
        process.env.SUPABASE_URL!,
        process.env.SUPABASE_ANON_KEY!,
        {
          global: {
            headers: { Authorization: `Bearer ${session.session.access_token}` },
          },
        },
      )

      // Check idempotency
      const { data: existing } = await supabase
        .from('quote_requests')
        .select('id, request_number')
        .eq('idempotency_key', input.idempotencyKey)
        .maybeSingle()

      if (existing) {
        return {
          requestId: existing.id,
          reference: existing.request_number,
        }
      }

      const status = input.approvalRequired ? 'draft' : 'submitted'
      const submittedAt = input.approvalRequired ? null : new Date().toISOString()

      // Insert quote request (request_number auto-generated by trigger)
      const { data: qr, error: qrError } = await supabase
        .from('quote_requests')
        .insert({
          customer_id: session.user.app_metadata?.customer_id,
          status,
          urgency: 'standard',
          project_id: input.projectId ?? null,
          delivery_address_id: input.deliveryAddressId ?? null,
          delivery_date: input.deliveryDate ?? null,
          notes: input.notes ?? null,
          attachment_urls: input.attachmentUrls ?? [],
          submitted_at: submittedAt,
          submitted_by: session.user.id,
          idempotency_key: input.idempotencyKey,
          approval_required: input.approvalRequired ?? false,
        })
        .select('id, request_number')
        .single()

      if (qrError || !qr) {
        throw new Error(qrError?.message ?? 'Failed to create quote request')
      }

      // Insert items
      const itemRows = input.items.map((item) => ({
        quote_request_id: qr.id,
        product_id: item.productId ?? null,
        customer_description: item.customerDescription,
        quantity: item.quantity,
        unit_of_measure: item.unitOfMeasure,
        notes: item.notes ?? null,
        match_confidence: item.matchConfidence ?? null,
        sort_order: item.sortOrder,
        is_unmatched: item.isUnmatched ?? false,
      }))

      const { error: itemsError } = await supabase
        .from('quote_request_items')
        .insert(itemRows)

      if (itemsError) {
        throw new Error(itemsError.message)
      }

      // If approval required, create approval record
      if (input.approvalRequired) {
        await supabase.from('approvals').insert({
          approval_type: 'quote_discount',
          entity_type: 'quote_request',
          entity_id: qr.id,
          requested_by: session.user.id,
          assigned_to: session.user.id, // Placeholder; real approver assigned by workflow
          status: 'pending',
          context: { items_count: input.items.length },
        })
      }

      return {
        requestId: qr.id,
        reference: qr.request_number,
      }
    },
  )

// ============================================================================
// saveDraft
// ============================================================================

export const saveDraft = createServerFn()
  .inputValidator(saveDraftInput)
  .handler(async ({ data: input }): Promise<{ draftId: string }> => {
    // Dev mode fallback
    if (!isSupabaseConfigured()) {
      return { draftId: input.draftId ?? crypto.randomUUID() }
    }

    const session = await getServerSession({
      supabaseUrl: process.env.SUPABASE_URL!,
      supabaseAnonKey: process.env.SUPABASE_ANON_KEY!,
    })

    if (!session) {
      throw new Error('Unauthorized')
    }

    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_ANON_KEY!,
      {
        global: {
          headers: { Authorization: `Bearer ${session.session.access_token}` },
        },
      },
    )

    if (input.draftId) {
      // Update existing draft
      const { error } = await supabase
        .from('quote_requests')
        .update({
          project_id: input.projectId ?? null,
          delivery_address_id: input.deliveryAddressId ?? null,
          delivery_date: input.deliveryDate ?? null,
          notes: input.notes ?? null,
          attachment_urls: input.attachmentUrls ?? [],
        })
        .eq('id', input.draftId)
        .eq('status', 'draft')

      if (error) throw new Error(error.message)

      // Replace items
      await supabase
        .from('quote_request_items')
        .delete()
        .eq('quote_request_id', input.draftId)

      if (input.items.length > 0) {
        await supabase.from('quote_request_items').insert(
          input.items.map((item) => ({
            quote_request_id: input.draftId,
            product_id: item.productId ?? null,
            customer_description: item.customerDescription,
            quantity: item.quantity,
            unit_of_measure: item.unitOfMeasure,
            notes: item.notes ?? null,
            match_confidence: item.matchConfidence ?? null,
            sort_order: item.sortOrder,
            is_unmatched: item.isUnmatched ?? false,
          })),
        )
      }

      return { draftId: input.draftId }
    }

    // Create new draft
    const { data: qr, error: qrError } = await supabase
      .from('quote_requests')
      .insert({
        customer_id: session.user.app_metadata?.customer_id,
        status: 'draft',
        project_id: input.projectId ?? null,
        delivery_address_id: input.deliveryAddressId ?? null,
        delivery_date: input.deliveryDate ?? null,
        notes: input.notes ?? null,
        attachment_urls: input.attachmentUrls ?? [],
      })
      .select('id')
      .single()

    if (qrError || !qr) {
      throw new Error(qrError?.message ?? 'Failed to create draft')
    }

    if (input.items.length > 0) {
      await supabase.from('quote_request_items').insert(
        input.items.map((item) => ({
          quote_request_id: qr.id,
          product_id: item.productId ?? null,
          customer_description: item.customerDescription,
          quantity: item.quantity,
          unit_of_measure: item.unitOfMeasure,
          notes: item.notes ?? null,
          match_confidence: item.matchConfidence ?? null,
          sort_order: item.sortOrder,
          is_unmatched: item.isUnmatched ?? false,
        })),
      )
    }

    return { draftId: qr.id }
  })

// ============================================================================
// getDrafts
// ============================================================================

export const getDrafts = createServerFn().handler(
  async (): Promise<
    Array<{
      id: string
      requestNumber: string
      notes: string | null
      updatedAt: string
      itemCount: number
    }>
  > => {
    // Dev mode fallback
    if (!isSupabaseConfigured()) {
      return []
    }

    const session = await getServerSession({
      supabaseUrl: process.env.SUPABASE_URL!,
      supabaseAnonKey: process.env.SUPABASE_ANON_KEY!,
    })

    if (!session) {
      throw new Error('Unauthorized')
    }

    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_ANON_KEY!,
      {
        global: {
          headers: { Authorization: `Bearer ${session.session.access_token}` },
        },
      },
    )

    const { data, error } = await supabase
      .from('quote_requests')
      .select('id, request_number, notes, updated_at, quote_request_items(count)')
      .eq('status', 'draft')
      .order('updated_at', { ascending: false })

    if (error) throw new Error(error.message)

    return (data ?? []).map((d) => ({
      id: d.id,
      requestNumber: d.request_number,
      notes: d.notes,
      updatedAt: d.updated_at,
      itemCount:
        (d.quote_request_items as unknown as Array<{ count: number }>)?.[0]
          ?.count ?? 0,
    }))
  },
)

// ============================================================================
// parseWithAI — mock implementation, Phase 30 swaps with real AI
// ============================================================================

const MATERIAL_KEYWORDS: Record<
  string,
  { name: string; uom: string }
> = {
  cement: { name: 'Portland Cement OPC 42.5N', uom: 'ton' },
  rebar: { name: 'Steel Rebar 16mm Grade 60', uom: 'ton' },
  plywood: { name: 'Plywood 18mm', uom: 'sheet' },
  sand: { name: 'Washed Sand', uom: 'cubic_meter' },
  gravel: { name: 'Crushed Gravel 20mm', uom: 'cubic_meter' },
  brick: { name: 'Red Clay Brick', uom: 'piece' },
  block: { name: 'Concrete Block 20cm', uom: 'piece' },
  tile: { name: 'Ceramic Floor Tile 60x60', uom: 'square_meter' },
  paint: { name: 'Exterior Wall Paint', uom: 'liter' },
  pipe: { name: 'PVC Pipe 4 inch', uom: 'meter' },
  cable: { name: 'Electrical Cable 2.5mm', uom: 'meter' },
  gypsum: { name: 'Gypsum Board 12mm', uom: 'sheet' },
  steel: { name: 'Structural Steel', uom: 'ton' },
  aggregate: { name: 'Aggregate', uom: 'cubic_meter' },
  insulation: { name: 'Thermal Insulation', uom: 'square_meter' },
  waterproofing: { name: 'Bitumen Waterproofing Membrane', uom: 'roll' },
  // Arabic keywords
  '\u0627\u0633\u0645\u0646\u062a': { name: 'Portland Cement OPC 42.5N', uom: 'ton' },
  '\u062d\u062f\u064a\u062f': { name: 'Steel Rebar 16mm Grade 60', uom: 'ton' },
  '\u0631\u0645\u0644': { name: 'Washed Sand', uom: 'cubic_meter' },
  '\u0637\u0648\u0628': { name: 'Red Clay Brick', uom: 'piece' },
  '\u0628\u0644\u0627\u0637': { name: 'Ceramic Floor Tile 60x60', uom: 'square_meter' },
  '\u062f\u0647\u0627\u0646': { name: 'Exterior Wall Paint', uom: 'liter' },
  '\u0623\u0633\u0644\u0627\u0643': { name: 'Electrical Cable 2.5mm', uom: 'meter' },
  '\u0645\u0648\u0627\u0633\u064a\u0631': { name: 'PVC Pipe 4 inch', uom: 'meter' },
  '\u0623\u0633\u0645\u0646\u062a': { name: 'Portland Cement OPC 42.5N', uom: 'ton' },
}

export const parseWithAI = createServerFn()
  .inputValidator(parseWithAIInput)
  .handler(
    async ({
      data: input,
    }): Promise<{ parsedItems: ParsedItem[] }> => {
      // Mock implementation: extract quantities and materials from text
      const lines = input.text
        .split('\n')
        .map((l) => l.trim())
        .filter(Boolean)
      const parsedItems: ParsedItem[] = []

      for (const line of lines) {
        const lower = line.toLowerCase()
        // Try to extract quantity (any number in the line)
        const qtyMatch = line.match(/(\d+(?:\.\d+)?)\s*(?:ton|kg|m|pcs?|bags?|sheets?)?/i)
        const quantity = qtyMatch ? parseFloat(qtyMatch[1]) : 1

        // Find matching material keyword
        let matched = false
        for (const [keyword, material] of Object.entries(MATERIAL_KEYWORDS)) {
          if (lower.includes(keyword)) {
            parsedItems.push({
              productName: material.name,
              quantity,
              unitOfMeasure: material.uom,
              notes: line,
              matchConfidence: 0.8,
            })
            matched = true
            break
          }
        }

        // If no keyword matched, add as unmatched
        if (!matched && line.length > 2) {
          parsedItems.push({
            productName: line,
            quantity,
            unitOfMeasure: 'piece',
            notes: line,
            matchConfidence: 0.3,
          })
        }
      }

      return { parsedItems }
    },
  )
